### ISSUE TITLE
[Feature Request] List view and option to put the sidebar on top

### ISSUE THREAD

**Issue by GlazedBelmont** [Flutterando/yuno#6]
As the title says, I love the UI but more customization would be extremely welcome. You could think of it as like the list view of Beacon and how Beacon puts its sidebar

**Comment by jacobaraujo7** [comment]
Hello.
One of the things that really bothered me about Beacon is having the categories tab at the top on 21:9 cell phones, causing the sensation of vertical loss on these screens, which is why I chose to place it on the side. But maybe using the list type this makes more sense.
I personally don't really like the list view, but I agree that having the option will help a lot.

At first I'll add the option to remove the All and Favorites tabs, then I'll think about how to change the layout of the games' current presentation.

**Comment by GlaZedBelmont** [comment]
ah yeah on longer displays, it'll look odd, I'm on a 16:9 one so it never really bothered me

**Comment by jacobaraujo7** [comment]
Added build-24

**Comment by GlazedBelmont** [comment]
Haven't found the apk on build-24 just yet
